version: "3.9"

services:
  redpanda:
    image: redpandadata/redpanda:v23.3.3
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    networks:
      - log-net

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - log-net

  minio:
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"
      - "9002:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    networks:
      - log-net

networks:
  log-net:
    driver: bridge

volumes:
  clickhouse-data:
  minio-data:
