version: "3.9"

services:
  redpanda:
    image: vectorized/redpanda:v23.3.12
    container_name: redpanda
    command: >
      redpanda start
      --overprovisioned
      --smp 1
      --memory 1G
      --reserve-memory 0M
      --node-id 0
      --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9644/ready"]
      interval: 5s
      retries: 10
      start_period: 10s
    networks:
      - infra_net

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - infra_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 5s
      retries: 10
      start_period: 10s

  ingestion-api:
    build:
      context: ../ingestion-api 
      dockerfile: Dockerfile
    container_name: ingestion-api
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    depends_on:
      redpanda:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - infra_net
    ports:
      - "8000:8000"

networks:
  infra_net:
    driver: bridge
